"""Adding chat room and messages added

Revision ID: 0750bea19b84
Revises: e34ce6636b81
Create Date: 2024-06-21 16:31:09.431827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0750bea19b84'
down_revision: Union[str, None] = 'e34ce6636b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('sender_id', sa.String(), nullable=False))
    op.add_column('chat_rooms', sa.Column('sender_type', sa.String(), nullable=False))
    op.add_column('chat_rooms', sa.Column('receiver_id', sa.String(), nullable=False))
    op.add_column('chat_rooms', sa.Column('receiver_type', sa.String(), nullable=False))
    op.drop_constraint('chat_rooms_user_id_fkey', 'chat_rooms', type_='foreignkey')
    op.drop_constraint('chat_rooms_service_provider_id_fkey', 'chat_rooms', type_='foreignkey')
    op.drop_column('chat_rooms', 'service_provider_id')
    op.drop_column('chat_rooms', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chat_rooms', sa.Column('service_provider_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('chat_rooms_service_provider_id_fkey', 'chat_rooms', 'serviceProvider', ['service_provider_id'], ['service_provider_id'])
    op.create_foreign_key('chat_rooms_user_id_fkey', 'chat_rooms', 'users', ['user_id'], ['user_id'])
    op.drop_column('chat_rooms', 'receiver_type')
    op.drop_column('chat_rooms', 'receiver_id')
    op.drop_column('chat_rooms', 'sender_type')
    op.drop_column('chat_rooms', 'sender_id')
    # ### end Alembic commands ###
