"""CREATING A REJECTED ORDER TABLE

Revision ID: 0e8a7082dbce
Revises: c5ec3018210e
Create Date: 2024-05-06 17:00:15.753875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8a7082dbce'
down_revision: Union[str, None] = 'c5ec3018210e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejectedOrder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_provider_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_provider_id'], ['serviceProvider.service_provider_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rejectedOrder')
    # ### end Alembic commands ###
