"""adding is_verified to the user table

Revision ID: 1ce289e1c729
Revises: 10a1bbdd3fbd
Create Date: 2024-05-20 01:57:01.831289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce289e1c729'
down_revision: Union[str, None] = '10a1bbdd3fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
