"""adding payment Intent table

Revision ID: 3624c08d26dc
Revises: 36fd6fe41a7a
Create Date: 2024-05-23 14:02:07.522613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3624c08d26dc'
down_revision: Union[str, None] = '36fd6fe41a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_intents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_payment_intents_id', 'payment_intents', ['id'], unique=False)
    op.alter_column('payment_intents', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
