"""adding payment Intent id to orders

Revision ID: 3c22c17e7bf7
Revises: c856d16b3fa4
Create Date: 2024-05-25 17:57:04.518120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c22c17e7bf7'
down_revision: Union[str, None] = 'c856d16b3fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_intent_id', sa.String(), server_default='N/A', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_intent_id')
    # ### end Alembic commands ###
