"""adding rejected service provider to orders

Revision ID: 3f7acfa3eee2
Revises: cad3cec296c6
Create Date: 2024-05-06 00:40:50.727645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7acfa3eee2'
down_revision: Union[str, None] = 'cad3cec296c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders","rejectedServiceProvider")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
