"""changing phone_no vendor to string

Revision ID: 516edf785438
Revises: 3c22c17e7bf7
Create Date: 2024-06-20 00:45:59.145081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516edf785438'
down_revision: Union[str, None] = '3c22c17e7bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('serviceProvider', 'phone_no',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('serviceProvider', 'phone_no',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
