"""adding rejected service provider to orders

Revision ID: 711b8896f3d1
Revises: aae292ebd09e
Create Date: 2024-05-05 21:43:37.372405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711b8896f3d1'
down_revision: Union[str, None] = 'aae292ebd09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
