"""creating tables

Revision ID: 7263c2838339
Revises: 8e69518ad237
Create Date: 2024-03-22 16:25:29.577950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7263c2838339'
down_revision: Union[str, None] = '8e69518ad237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('quote_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['order_id'])
    op.create_foreign_key(None, 'orders', 'quotes', ['quote_id'], ['quote_id'])
    op.create_unique_constraint(None, 'quotes', ['quote_id'])
    op.create_unique_constraint(None, 'serviceProvider', ['service_provider_id'])
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'serviceProvider', type_='unique')
    op.drop_constraint(None, 'quotes', type_='unique')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'quote_id')
    # ### end Alembic commands ###
