"""added expiring time for  otp to users and service providers

Revision ID: 77295baf5d74
Revises: 554e31b130f2
Create Date: 2024-06-21 11:10:21.546489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77295baf5d74'
down_revision: Union[str, None] = '554e31b130f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serviceProvider', sa.Column('otp_expiry', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('otp_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expiry')
    op.drop_column('serviceProvider', 'otp_expiry')
    # ### end Alembic commands ###
