"""creating tables

Revision ID: 8e69518ad237
Revises: 
Create Date: 2024-03-22 16:20:42.718878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e69518ad237'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), server_default='N/A', nullable=False),
    sa.Column('company_url', sa.String(), server_default='N/A', nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('country', sa.String(), server_default='N/A', nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_no', sa.String(), nullable=False),
    sa.Column('user_type', sa.String(), server_default='user', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('serviceProvider',
    sa.Column('service_provider_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), server_default='N/A', nullable=False),
    sa.Column('company_url', sa.String(), server_default='N/A', nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('service_offered', sa.String(), nullable=False),
    sa.Column('street_address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), server_default='N', nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('user_type', sa.String(), server_default='service provider', nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('phone_no', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('service_provider_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_no'),
    sa.UniqueConstraint('service_provider_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_title', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('equipment_Category', sa.String(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.Column('dimension_length', sa.String(), server_default='N/A', nullable=False),
    sa.Column('dimension_width', sa.String(), server_default='N/A', nullable=False),
    sa.Column('dimension_weight', sa.String(), server_default='N/A', nullable=False),
    sa.Column('dimension_height', sa.String(), server_default='N/A', nullable=False),
    sa.Column('trailer_preference', sa.Boolean(), nullable=False),
    sa.Column('on_trailer', sa.Boolean(), nullable=False),
    sa.Column('collection_area', sa.String(), nullable=False),
    sa.Column('collection_location', sa.String(), nullable=False),
    sa.Column('loading_assistance', sa.Boolean(), nullable=False),
    sa.Column('date_of_collection', sa.String(), nullable=False),
    sa.Column('delivery_area', sa.String(), nullable=False),
    sa.Column('delivery_location', sa.String(), nullable=False),
    sa.Column('off_loading_assistance', sa.Boolean(), nullable=False),
    sa.Column('date_of_delivery', sa.String(), nullable=False),
    sa.Column('is_assigned', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('no_of_pieces', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('order_type', sa.String(), server_default='budget', nullable=False),
    sa.Column('bidding_budget', sa.String(), server_default='N/A', nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    # sa.Column('quote_id', sa.String(), nullable=True),
    sa.Column('budget', sa.String(), server_default='N/A', nullable=True),
    sa.Column('status', sa.String(), server_default='No Reaction', nullable=False),
    sa.Column('is_budget', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['serviceProvider.service_provider_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.user_id'], ),
    # sa.ForeignKeyConstraint(['quote_id'], ['quotes.quote_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('quotes',
    sa.Column('quote_id', sa.String(), nullable=False),
    sa.Column('service_provider_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('quote_amount', sa.Float(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_provider_id'], ['serviceProvider.service_provider_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_id'),
    sa.UniqueConstraint('quote_id')
    )
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('serviceProvider')
    op.drop_table('quotes')
    op.drop_table('orders')
    # ### end Alembic commands ###
