"""Stripe_id status for service provider

Revision ID: a94d66c74f11
Revises: b450e5fc1f24
Create Date: 2024-06-25 14:15:04.389027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94d66c74f11'
down_revision: Union[str, None] = 'b450e5fc1f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serviceProvider', sa.Column('stripeId_status', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serviceProvider', 'stripeId_status')
    # ### end Alembic commands ###
