"""adding rejected service provider to orders

Revision ID: aae292ebd09e
Revises: 80d8edccfa8c
Create Date: 2024-05-03 16:29:30.202826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae292ebd09e'
down_revision: Union[str, None] = '80d8edccfa8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('rejectedServiceProvider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'rejectedServiceProvider')
    # ### end Alembic commands ###
