"""Adding security questions and answers to users and service provider

Revision ID: b450e5fc1f24
Revises: 1928d5c80918
Create Date: 2024-06-22 17:44:54.636963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b450e5fc1f24'
down_revision: Union[str, None] = '1928d5c80918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sender_type')
    # ### end Alembic commands ###
