"""adding payment Intent table

Revision ID: ba03098eaf23
Revises: 3624c08d26dc
Create Date: 2024-05-23 14:08:56.109047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba03098eaf23'
down_revision: Union[str, None] = '3624c08d26dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_intents_id'), table_name='payment_intents')
    op.drop_table('payment_intents')
    # ### end Alembic commands ###
