"""adding rejected service provider to orders

Revision ID: c5ec3018210e
Revises: 3f7acfa3eee2
Create Date: 2024-05-06 00:43:11.593135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ec3018210e'
down_revision: Union[str, None] = '3f7acfa3eee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
