"""adding payment Intent table

Revision ID: c856d16b3fa4
Revises: 138bc3677b21
Create Date: 2024-05-23 16:10:31.967947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c856d16b3fa4'
down_revision: Union[str, None] = '138bc3677b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serviceProvider', sa.Column('stripe_account', sa.String(), server_default='N/A', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serviceProvider', 'stripe_account')
    # ### end Alembic commands ###
