"""adding rejected service provider to orders

Revision ID: cad3cec296c6
Revises: 204ac43c785e
Create Date: 2024-05-05 22:35:51.692683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad3cec296c6'
down_revision: Union[str, None] = '204ac43c785e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE orders ALTER COLUMN "rejectedServiceProvider" TYPE JSON USING "rejectedServiceProvider"::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'rejectedServiceProvider',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
